In [2]:
import torch
print(torch.__version__)

/Users/navdeep/Desktop/Deep-Learning/venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


2.6.0


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


Creating a tensor

In [4]:
# using empty
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
# check type
a = torch.empty(2, 3)
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2, 3)

tensor([[0.4478, 0.7305, 0.8264],
        [0.8600, 0.6394, 0.5273]])

In [9]:
# use of seed
torch.rand(2, 3)

tensor([[6.6061e-01, 5.9106e-01, 8.9828e-01],
        [4.7861e-01, 9.3156e-04, 9.7579e-01]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# other ways

# arange
print("using arange ->", torch.arange(0, 10, 2))

# using linspace
print("using linspace ->", torch.linspace(0, 10, 10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [14]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor data types

In [20]:
# find data type
x.dtype

torch.int64

In [21]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [22]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [23]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operations

1. Scalar operation

In [24]:
x = torch.rand(2, 2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [25]:
# addition
x + 2
# subtraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
((x * 100) // 3)%2
# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

Element wise operation

In [26]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [27]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [28]:
c = torch.tensor([1, -2, 3, -4])

In [29]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [30]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [31]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [32]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [35]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [58]:
e = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 6., 7.],
        [7., 8., 3.]])

In [59]:
# sum
torch.sum(e)

tensor(33.)

In [60]:
# sum along columns
torch.sum(e, dim=0)

tensor([ 9., 14., 10.])

In [61]:
# sum along rows
torch.sum(e, dim=1)

tensor([15., 18.])

In [41]:
# mean
torch.mean(e)

tensor(4.6667)

In [42]:
# mean along column
torch.mean(e, dim=0)

tensor([7.0000, 5.5000, 1.5000])

In [43]:
# median
torch.median(e)

tensor(4.)

In [44]:
# max and min
torch.max(e)

tensor(9.)

In [45]:
torch.min(e)

tensor(0.)

In [46]:
# product
torch.prod(e)

tensor(0.)

In [47]:
# standard deviation
torch.std(e)

tensor(3.1411)

In [48]:
# variance
torch.var(e)

tensor(9.8667)

In [49]:
# argmax
torch.argmax(e)

tensor(3)

In [50]:
# argmin
torch.argmin(e)

tensor(5)

4. Matrix operations

In [51]:
f = torch.randint(size=(2, 3), low=0, high=10)
g = torch.randint(size=(3, 2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 5],
        [9, 9, 7]])
tensor([[5, 9],
        [8, 9],
        [7, 9]])


In [52]:
# matrix multiplication
torch.matmul(f, g)

tensor([[116, 153],
        [166, 225]])

In [53]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [54]:
# dot product 
torch.dot(vector1, vector2)

tensor(11)

In [57]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 9],
        [5, 7]])

In [62]:
h = torch.randint(size=(3, 3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [63]:
# determinant
torch.det(h)

tensor(-20.0000)

In [64]:
# inverse
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

5. Comparison operations

In [65]:
i = torch.randint(size=(2, 3), low=0, high=10)
j = torch.randint(size=(2, 3), low=0, high=10)

print(i)
print(j)

tensor([[3, 3, 5],
        [0, 6, 4]])
tensor([[0, 8, 4],
        [7, 2, 3]])


In [66]:
# greater than
i > j

tensor([[ True, False,  True],
        [False,  True,  True]])

In [67]:
# less than
i < j

tensor([[False,  True, False],
        [ True, False, False]])

In [68]:
# equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [69]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [70]:
# greater than equal to

In [71]:
# less than equal to

6. Special fuctions

In [77]:
k = torch.randint(size=(2, 3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [73]:
# log
torch.log(k)

tensor([[2.0794, 1.6094, 1.7918],
        [0.6931, 2.1972, 1.6094]])

In [74]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02, 4.0343e+02],
        [7.3891e+00, 8.1031e+03, 1.4841e+02]])

In [75]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361, 2.4495],
        [1.4142, 3.0000, 2.2361]])

In [76]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933, 0.9975],
        [0.8808, 0.9999, 0.9933]])

In [78]:
# softmax
torch.softmax(k, dim=0)

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

In [79]:
# relu
torch.relu(k)

tensor([[0., 4., 2.],
        [7., 1., 1.]])

Inplace Operations

In [80]:
m = torch.rand(2, 3)
n = torch.rand(2, 3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [83]:
m.add_(n) # inplace addition

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [84]:
m 

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [85]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [86]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [87]:
m.relu_() # inplace modification

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [88]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

Copying a Tensor

In [89]:
a = torch.rand(2, 3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [90]:
b = a

In [91]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [92]:
a[0][0] = 0

In [93]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [94]:
b # b is also modified -> not desirable

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [95]:
id(a)

4496068032

In [96]:
id(b) # same memory location

4496068032

In [97]:
b = a.clone()

In [98]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [99]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [100]:
a[0][0] = 10

In [101]:
a

tensor([[10.0000,  0.0340,  0.9157],
        [ 0.3079,  0.6269,  0.8277]])

In [102]:
b # no modification now because b is in different memory location

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [103]:
id(a)

4496068032

In [104]:
id(b)

4496456224

Tensor Operations on GPU

In [109]:
# torch.cuda.is_available()
torch.backends.mps.is_available()

True

In [110]:
device = torch.device("mps")

In [111]:
# creating a new tensor on GPU
torch.rand((2, 3), device=device)

tensor([[0.4643, 0.8532, 0.4872],
        [0.4602, 0.4261, 0.0968]], device='mps:0')

In [112]:
# moving an existing tensor to GPU
a = torch.rand(2, 3) 
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [114]:
b = a.to(device=device)

In [115]:
b + 5 # operation on gpu

tensor([[5.6594, 5.0887, 5.4890],
        [5.5887, 5.7340, 5.8497]], device='mps:0')

Reshaping Tensors

In [116]:
a = torch.ones(4, 4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [117]:
# reshape
a.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [118]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [120]:
b = torch.rand(2, 3, 4)
b

tensor([[[0.9112, 0.4847, 0.9436, 0.3904],
         [0.2499, 0.3206, 0.9753, 0.7582],
         [0.6688, 0.2651, 0.2336, 0.5057]],

        [[0.5688, 0.0634, 0.8993, 0.2732],
         [0.3397, 0.1879, 0.5534, 0.2682],
         [0.9556, 0.9761, 0.5934, 0.3124]]])

In [121]:
# permute
b.permute(2, 0, 1).shape

torch.Size([4, 2, 3])

In [122]:
b.permute(2, 0, 1)

tensor([[[0.9112, 0.2499, 0.6688],
         [0.5688, 0.3397, 0.9556]],

        [[0.4847, 0.3206, 0.2651],
         [0.0634, 0.1879, 0.9761]],

        [[0.9436, 0.9753, 0.2336],
         [0.8993, 0.5534, 0.5934]],

        [[0.3904, 0.7582, 0.5057],
         [0.2732, 0.2682, 0.3124]]])

In [123]:
# unsquuze -> used to add batches
c = torch.rand(226, 226, 3) # image size
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [128]:
# squeeze
d = torch.rand(1,20)
print(d)
d.squeeze(0)

tensor([[0.8246, 0.4808, 0.4908, 0.9845, 0.0086, 0.6571, 0.4712, 0.9309, 0.7066,
         0.2748, 0.6709, 0.8614, 0.3422, 0.3894, 0.7697, 0.5311, 0.0036, 0.9329,
         0.0286, 0.5952]])


tensor([0.8246, 0.4808, 0.4908, 0.9845, 0.0086, 0.6571, 0.4712, 0.9309, 0.7066,
        0.2748, 0.6709, 0.8614, 0.3422, 0.3894, 0.7697, 0.5311, 0.0036, 0.9329,
        0.0286, 0.5952])

In [127]:
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [4]:
import torch
import numpy as np

In [5]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [6]:
b = a.numpy() # convert pytorch tensor to numy array
b

array([1, 2, 3])

In [7]:
type(b)

numpy.ndarray

In [8]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [9]:
torch.from_numpy(c)

tensor([1, 2, 3])