<a href="https://colab.research.google.com/github/NavdeepTU/Deep-Learning/blob/main/01.%20Quickstart_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Set up Tensorflow

In [ ]:
import tensorflow as tf
print('Tensorflow version ', tf.__version__)

Tensorflow version  2.14.0


Load a Dataset

In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
print("Train size", x_train.shape)
print("Test size", x_test.shape)

Train size (60000, 28, 28)
Test size (10000, 28, 28)


Building a Machine Learning Model

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.074716  ,  0.0668287 ,  0.7333134 , -0.8669623 , -0.34843493,
         0.28014457, -0.00408596,  0.06921738, -0.48568493, -0.43265766]],
      dtype=float32)

In [ ]:
# The tf.nn.softmax function converts these logits to probabilities for each class
tf.nn.softmax(predictions).numpy()

array([[0.09411764, 0.10842841, 0.21115129, 0.04261896, 0.07158078,
        0.13421004, 0.10100555, 0.10868772, 0.06240071, 0.06579895]],
      dtype=float32)

In [ ]:
# Define the loss function for training
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.0083492

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate your model

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3008 - accuracy: 0.9125
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1445 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1085 - accuracy: 0.9671
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0899 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0741 - accuracy: 0.9770


In [ ]:
model.evaluate(x_test, y_test, verbose=2) # The image classifier is now trained to ~98% accuracy on this dataset.

313/313 - 1s - loss: 0.0728 - accuracy: 0.9775 - 1s/epoch - 4ms/step


[0.07282765954732895, 0.9775000214576721]

In [ ]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.8105155e-07, 6.5911108e-09, 1.4778609e-06, 9.1856818e-06,
        4.8643711e-11, 4.5048768e-08, 3.6575482e-14, 9.9998617e-01,
        4.7822180e-08, 2.9833036e-06],
       [3.2236487e-09, 1.6354595e-04, 9.9980694e-01, 2.1293654e-05,
        5.6928613e-16, 8.1025109e-06, 1.3198866e-07, 1.0888476e-13,
        2.5550445e-08, 2.8200234e-14],
       [3.1467167e-07, 9.9964225e-01, 7.3906922e-05, 1.5404075e-05,
        1.6802844e-05, 1.3440505e-05, 6.0639545e-06, 1.3707537e-04,
        9.3758426e-05, 8.8972172e-07],
       [9.9982738e-01, 8.8335472e-09, 1.2234740e-04, 2.7110622e-07,
        6.2443156e-08, 2.5085832e-05, 5.1746980e-07, 2.1078054e-06,
        1.3467238e-08, 2.2008664e-05],
       [3.1129455e-06, 8.9212220e-09, 2.6687014e-06, 5.2690126e-08,
        9.9356341e-01, 3.4211453e-08, 3.3458266e-06, 1.5318743e-05,
        1.3044421e-06, 6.4107990e-03]], dtype=float32)>